backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

- name: "products"
  label: "Products"
  folder: "src/pages/products"
  create: true
  identifier_field: name
  fields:
  - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page-template"}
  - {label: "ID", name: "id", widget: "string"}
  - {label: "Title", name: "title", widget: "string"}
#  - {label: "Price", name: "price", widget: "string"}
  - {label: "Description", name: "description", widget: "markdown", required: false}
  - {label: "Featured Image", name: "featuredimage", widget: image}
  - label: "Gallery"
    name: "images"
    widget: "list"
    field: {label: Image, name: image, widget: image}
    required: false
  - label: "Variants"
    name: "variants"
    widget: "list"
    fields:
      - label: sku
        name: skuAttr
        widget: string
        required: true

      - label: Price
        name: discount
        widget: string
        required: true

      - label: Compare At
        name: pricing
        widget: string
        required: false

      - label: Option Combination
        name: combinedAttributes
        widget: list
        required: false
        field: {label: Option, name: option, widget: string}
  - {label: "Tags", name: "tags", widget: "list", required: false}
  - {label: "Origin_link", name: "origin_link", widget: "string", required: false}

- name: "pages"
  label: "Pages"
  files:
  - file: "src/pages/index.md"
    label: "Landing Page"
    name: "index"
    fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Heading, name: heading, widget: string}
    - {label: Subheading, name: subheading, widget: string}
    - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
    - {label: Description, name: description, widget: string}
    - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
    - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
  - file: "src/pages/about/index.md"
    label: "About"
    name: "about"
    fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
